"""Add models and data

Revision ID: e35568aba320
Revises: 
Create Date: 2022-09-18 16:51:06.649175

"""
from hashlib import sha256

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e35568aba320'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    admins = op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    difficulties = op.create_table('difficulties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('right_answers_to_win', sa.Integer(), nullable=False),
    sa.Column('wrong_answers_to_lose', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_difficulties_id'), 'difficulties', ['id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vk_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('games_count', sa.Integer(), nullable=False),
    sa.Column('wins_count', sa.Integer(), nullable=False),
    sa.Column('loses_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vk_id')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    themes = op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_themes_id'), 'themes', ['id'], unique=False)
    questions = op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('difficulty_id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['difficulty_id'], ['difficulties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('started_by_vk_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('response_time', sa.Integer(), nullable=False),
    sa.Column('session_duration', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('start_message_id', sa.Integer(), nullable=True),
    sa.Column('answering_player_vk_id', sa.Integer(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['winner_id'], ['players.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_message_id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    answers = op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_id'), 'answers', ['id'], unique=False)
    op.create_table('players_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('difficulty_id', sa.Integer(), nullable=False),
    sa.Column('right_answers', sa.Integer(), nullable=False),
    sa.Column('wrong_answers', sa.Integer(), nullable=False),
    sa.Column('is_won', sa.Boolean(), nullable=False),
    sa.Column('is_lost', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['difficulty_id'], ['difficulties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_status_id'), 'players_status', ['id'], unique=False)
    # ### end Alembic commands ###
    op.bulk_insert(admins,
                   [
                       {
                           "id": 1,
                           "email": "test@test.ru",
                           "password": sha256("1234".encode()).hexdigest()
                       },
                       {
                           "id": 2,
                           "email": "admin@admin.com",
                           "password": sha256("admin".encode()).hexdigest()
                       }
                   ]
                   )

    op.bulk_insert(difficulties,
                   [
                       {
                           "id": 1,
                           "title": "Красный",
                           "right_answers_to_win": 1,
                           "wrong_answers_to_lose": 1
                       },
                       {
                           "id": 2,
                           "title": "Желтый",
                           "right_answers_to_win": 2,
                           "wrong_answers_to_lose": 2
                       },
                       {
                           "id": 3,
                           "title": "Зеленый",
                           "right_answers_to_win": 3,
                           "wrong_answers_to_lose": 3
                       }
                   ]
                   )

    op.bulk_insert(themes,
                   [
                       {
                           "id": 1,
                           "title": "Природа"
                       },
                       {
                           "id": 2,
                           "title": "Литература"
                       },
                       {
                           "id": 3,
                           "title": "Кино"
                       },
                       # {
                       #     "id": 4,
                       #     "title": "Города и страны"
                       # },
                       # {
                       #     "id": 5,
                       #     "title": "Сериалы"
                       # },
                       # {
                       #     "id": 6,
                       #     "title": "Аниме"
                       # },
                       # {
                       #     "id": 7,
                       #     "title": "История"
                       # },
                       # {
                       #     "id": 8,
                       #     "title": "Спорт"
                       # },
                       #
                       # {
                       #     "id": 9,
                       #     "title": "Наука"
                       # },
                       #
                       # {
                       #     "id": 10,
                       #     "title": "Техника"
                       # }
                   ]
                   )

    op.bulk_insert(questions,
                   [
                       {
                           "id": 1,
                           "title": "Крупнейший океан на планете?",
                           "difficulty_id": 3,
                           "theme_id": 1
                       },
                       {
                           "id": 2,
                           "title": "Крупнейший материк на планете?",
                           "difficulty_id": 3,
                           "theme_id": 1
                       },
                       {
                           "id": 3,
                           "title": "Самый маленький континент?",
                           "difficulty_id": 3,
                           "theme_id": 1
                       },
                       {
                           "id": 4,
                           "title": "Самый высокий горный массив?",
                           "difficulty_id": 2,
                           "theme_id": 1
                       },
                       {
                           "id": 5,
                           "title": "Самое большое озеро в мире?",
                           "difficulty_id": 2,
                           "theme_id": 1
                       },
                       {
                           "id": 6,
                           "title": "Крупнейшее млекопитающее?",
                           "difficulty_id": 2,
                           "theme_id": 1
                       },
                       {
                           "id": 7,
                           "title": "Крупнейшая птица в мире?",
                           "difficulty_id": 1,
                           "theme_id": 1
                       },
                       {
                           "id": 8,
                           "title": "Самая длинная река?",
                           "difficulty_id": 1,
                           "theme_id": 1
                       },
                       {
                           "id": 9,
                           "title": "Самый высокий вулкан в мире?",
                           "difficulty_id": 1,
                           "theme_id": 1
                       },
                       {
                           "id": 10,
                           "title": "Автор произведения \"Война и мир\"?",
                           "difficulty_id": 3,
                           "theme_id": 2
                       },
                       {
                           "id": 11,
                           "title": "Кто из них не является поэтом?",
                           "difficulty_id": 3,
                           "theme_id": 2
                       },
                       {
                           "id": 12,
                           "title": "Автор стихотворения \"Бородино\"?",
                           "difficulty_id": 3,
                           "theme_id": 2
                       },
                       {
                           "id": 13,
                           "title": "Автор произведения \"Отцы и дети\"?",
                           "difficulty_id": 2,
                           "theme_id": 2
                       },
                       {
                           "id": 14,
                           "title": "Автор произведения \"Мастер и Маргарита\"?",
                           "difficulty_id": 2,
                           "theme_id": 2
                       },
                       {
                           "id": 15,
                           "title": "Главный герой произведения \"Герой нашего времени\"?",
                           "difficulty_id": 2,
                           "theme_id": 2
                       },
                       {
                           "id": 16,
                           "title": "Автор произведения \"Декамерон\"?",
                           "difficulty_id": 1,
                           "theme_id": 2
                       },
                       {
                           "id": 17,
                           "title": "Главный герой произведения \"Преступление и наказание\"?",
                           "difficulty_id": 1,
                           "theme_id": 2
                       },

                       {
                           "id": 18,
                           "title": "Сколько лет пролежал на печи Илья Муромец?",
                           "difficulty_id": 1,
                           "theme_id": 2
                       },
                       {
                           "id": 19,
                           "title": "Актёр, сыгравший терминатора в одноимённом фильме?",
                           "difficulty_id": 3,
                           "theme_id": 3
                       },
                       {
                           "id": 20,
                           "title": "Какого Гендальфа не было в трилогии \"Властелин колец\"",
                           "difficulty_id": 3,
                           "theme_id": 3
                       },
                       {
                           "id": 21,
                           "title": "Главный Голливудский пират?",
                           "difficulty_id": 3,
                           "theme_id": 3
                       },
                       {
                           "id": 22,
                           "title": "Актёр, сыгравший главную роль в фильме \"Гладиатор\"?",
                           "difficulty_id": 2,
                           "theme_id": 3
                       },
                       {
                           "id": 23,
                           "title": "Режиссер фильма \"Джанго освобожденный\"?",
                           "difficulty_id": 2,
                           "theme_id": 3
                       },
                       {
                           "id": 24,
                           "title": "Главная премия в киноиндустрии?",
                           "difficulty_id": 2,
                           "theme_id": 3
                       },
                       {
                           "id": 25,
                           "title": "Один из фильмов с наибольшим количеством Оскаров?",
                           "difficulty_id": 1,
                           "theme_id": 3
                       },
                       {
                           "id": 26,
                           "title": "Режиссёр знаменитой комедии \"12 стульев\"?",
                           "difficulty_id": 1,
                           "theme_id": 3
                       },
                       {
                           "id": 27,
                           "title": "Герой, которого сыграл Брюс Уиллис в фильме \"Крепкий орешек\"?",
                           "difficulty_id": 1,
                           "theme_id": 3
                       },
                   ]
                   )

    op.bulk_insert(answers,
                   [
                       {
                           "id": 1,
                           "title": "Тихий",
                           "is_correct": True,
                           "question_id": 1
                       },
                       {
                           "id": 2,
                           "title": "Атлантический",
                           "is_correct": False,
                           "question_id": 1
                       },
                       {
                           "id": 3,
                           "title": "Индийский",
                           "is_correct": False,
                           "question_id": 1
                       },
                       {
                           "id": 4,
                           "title": "Евразия",
                           "is_correct": True,
                           "question_id": 2
                       },
                       {
                           "id": 5,
                           "title": "Австралия",
                           "is_correct": False,
                           "question_id": 2
                       },
                       {
                           "id": 6,
                           "title": "Антарктида",
                           "is_correct": False,
                           "question_id": 2
                       },
                       {
                           "id": 7,
                           "title": "Австралия",
                           "is_correct": True,
                           "question_id": 3
                       },
                       {
                           "id": 8,
                           "title": "Южная Америка",
                           "is_correct": False,
                           "question_id": 3
                       },
                       {
                           "id": 9,
                           "title": "Африка",
                           "is_correct": False,
                           "question_id": 3
                       },
                       {
                           "id": 10,
                           "title": "Гималаи",
                           "is_correct": True,
                           "question_id": 4
                       },
                       {
                           "id": 11,
                           "title": "Альпы",
                           "is_correct": False,
                           "question_id": 4
                       },
                       {
                           "id": 12,
                           "title": "Анды",
                           "is_correct": False,
                           "question_id": 4
                       },
                       {
                           "id": 13,
                           "title": "Каспийское море",
                           "is_correct": True,
                           "question_id": 5
                       },
                       {
                           "id": 14,
                           "title": "Байкал",
                           "is_correct": False,
                           "question_id": 5
                       },
                       {
                           "id": 15,
                           "title": "Ладожское озеро",
                           "is_correct": False,
                           "question_id": 5
                       },
                       {
                           "id": 16,
                           "title": "Синий кит",
                           "is_correct": True,
                           "question_id": 6
                       },
                       {
                           "id": 17,
                           "title": "Африканский слон",
                           "is_correct": False,
                           "question_id": 6
                       },
                       {
                           "id": 18,
                           "title": "Жираф",
                           "is_correct": False,
                           "question_id": 6
                       },
                       {
                           "id": 19,
                           "title": "Страус",
                           "is_correct": True,
                           "question_id": 7
                       },
                       {
                           "id": 20,
                           "title": "Пеликан",
                           "is_correct": False,
                           "question_id": 7
                       },
                       {
                           "id": 21,
                           "title": "Птеродактиль",
                           "is_correct": False,
                           "question_id": 7
                       },
                       {
                           "id": 22,
                           "title": "Амазонка",
                           "is_correct": True,
                           "question_id": 8
                       },
                       {
                           "id": 23,
                           "title": "Нил",
                           "is_correct": False,
                           "question_id": 8
                       },
                       {
                           "id": 24,
                           "title": "Миссисипи",
                           "is_correct": False,
                           "question_id": 8
                       },
                       {
                           "id": 25,
                           "title": "Охос-дель-Саладо",
                           "is_correct": True,
                           "question_id": 9
                       },
                       {
                           "id": 26,
                           "title": "Везувий",
                           "is_correct": False,
                           "question_id": 9
                       },
                       {
                           "id": 27,
                           "title": "Ключевская сопка",
                           "is_correct": False,
                           "question_id": 9
                       },
                       {
                           "id": 28,
                           "title": "Л.Н.Толстой",
                           "is_correct": True,
                           "question_id": 10
                       },
                       {
                           "id": 29,
                           "title": "А.С.Пушкин",
                           "is_correct": False,
                           "question_id": 10
                       },
                       {
                           "id": 30,
                           "title": "А.П.Чехов",
                           "is_correct": False,
                           "question_id": 10
                       },
                       {
                           "id": 31,
                           "title": "П.И.Чайковский",
                           "is_correct": True,
                           "question_id": 11
                       },
                       {
                           "id": 32,
                           "title": "М.Ю.Лермонтов",
                           "is_correct": False,
                           "question_id": 11
                       },
                       {
                           "id": 33,
                           "title": "А.С.Пушкин",
                           "is_correct": False,
                           "question_id": 11
                       },
                       {
                           "id": 34,
                           "title": "М.Ю.Лермонтов",
                           "is_correct": True,
                           "question_id": 12
                       },
                       {
                           "id": 35,
                           "title": "Л.Н.Толстой",
                           "is_correct": False,
                           "question_id": 12
                       },
                       {
                           "id": 36,
                           "title": "Ф.М.Достоевский",
                           "is_correct": False,
                           "question_id": 12
                       },
                       {
                           "id": 37,
                           "title": "И.С.Тургенев",
                           "is_correct": True,
                           "question_id": 13
                       },
                       {
                           "id": 38,
                           "title": "Л.Н.Толстой",
                           "is_correct": False,
                           "question_id": 13
                       },
                       {
                           "id": 39,
                           "title": "Н.В.Гоголь",
                           "is_correct": False,
                           "question_id": 13
                       },
                       {
                           "id": 40,
                           "title": "М.А.Булгаков",
                           "is_correct": True,
                           "question_id": 14
                       },
                       {
                           "id": 41,
                           "title": "Л.Н.Толстой",
                           "is_correct": False,
                           "question_id": 14
                       },
                       {
                           "id": 42,
                           "title": "Б.Л.Пастернак",
                           "is_correct": False,
                           "question_id": 14
                       },
                       {
                           "id": 43,
                           "title": "Печорин",
                           "is_correct": True,
                           "question_id": 15
                       },
                       {
                           "id": 44,
                           "title": "Онегин",
                           "is_correct": False,
                           "question_id": 15
                       },
                       {
                           "id": 45,
                           "title": "Безруков",
                           "is_correct": False,
                           "question_id": 15
                       },
                       {
                           "id": 46,
                           "title": "Джованни Бокаччо",
                           "is_correct": True,
                           "question_id": 16
                       },
                       {
                           "id": 47,
                           "title": "Мигель де Сервантес",
                           "is_correct": False,
                           "question_id": 16
                       },
                       {
                           "id": 48,
                           "title": "Данте Алигьери",
                           "is_correct": False,
                           "question_id": 16
                       },
                       {
                           "id": 49,
                           "title": "Раскольников",
                           "is_correct": True,
                           "question_id": 17
                       },
                       {
                           "id": 50,
                           "title": "Печорин",
                           "is_correct": False,
                           "question_id": 17
                       },
                       {
                           "id": 51,
                           "title": "Карамазов",
                           "is_correct": False,
                           "question_id": 17
                       },
                       {
                           "id": 52,
                           "title": "33 года",
                           "is_correct": True,
                           "question_id": 18
                       },
                       {
                           "id": 53,
                           "title": "40 лет",
                           "is_correct": False,
                           "question_id": 18
                       },
                       {
                           "id": 54,
                           "title": "10 лет",
                           "is_correct": False,
                           "question_id": 18
                       },
                       {
                           "id": 55,
                           "title": "Арнольд Шварценеггер",
                           "is_correct": True,
                           "question_id": 19
                       },
                       {
                           "id": 56,
                           "title": "Сильвестр Сталлоне",
                           "is_correct": False,
                           "question_id": 19
                       },
                       {
                           "id": 57,
                           "title": "Брэд Питт",
                           "is_correct": False,
                           "question_id": 19
                       },
                       {
                           "id": 58,
                           "title": "Синего",
                           "is_correct": True,
                           "question_id": 20
                       },
                       {
                           "id": 59,
                           "title": "Серого",
                           "is_correct": False,
                           "question_id": 20
                       },
                       {
                           "id": 60,
                           "title": "Белого",
                           "is_correct": False,
                           "question_id": 20
                       },
                       {
                           "id": 61,
                           "title": "Джек Воробей",
                           "is_correct": True,
                           "question_id": 21
                       },
                       {
                           "id": 62,
                           "title": "Пит Хромоног",
                           "is_correct": False,
                           "question_id": 21
                       },
                       {
                           "id": 63,
                           "title": "Гвидо Питонист",
                           "is_correct": False,
                           "question_id": 21
                       },
                       {
                           "id": 64,
                           "title": "Рассел Кроу",
                           "is_correct": True,
                           "question_id": 22
                       },
                       {
                           "id": 65,
                           "title": "Брэд Питт",
                           "is_correct": False,
                           "question_id": 22
                       },
                       {
                           "id": 66,
                           "title": "Кристиан Бэйл",
                           "is_correct": False,
                           "question_id": 22
                       },
                       {
                           "id": 67,
                           "title": "Квентин Тарантино",
                           "is_correct": True,
                           "question_id": 23
                       },
                       {
                           "id": 68,
                           "title": "Джосс Уидон",
                           "is_correct": False,
                           "question_id": 23
                       },
                       {
                           "id": 69,
                           "title": "Джеймс Кэмерон",
                           "is_correct": False,
                           "question_id": 23
                       },
                       {
                           "id": 70,
                           "title": "Оскар",
                           "is_correct": True,
                           "question_id": 24
                       },
                       {
                           "id": 71,
                           "title": "Эмми",
                           "is_correct": False,
                           "question_id": 24
                       },
                       {
                           "id": 72,
                           "title": "Золотая малина",
                           "is_correct": False,
                           "question_id": 24
                       },
                       {
                           "id": 73,
                           "title": "Бен Гур",
                           "is_correct": True,
                           "question_id": 25
                       },
                       {
                           "id": 74,
                           "title": "Аватар",
                           "is_correct": False,
                           "question_id": 25
                       },
                       {
                           "id": 75,
                           "title": "Интерстеллар",
                           "is_correct": False,
                           "question_id": 25
                       },
                       {
                           "id": 76,
                           "title": "Гайдай",
                           "is_correct": True,
                           "question_id": 26
                       },
                       {
                           "id": 77,
                           "title": "Рабинович",
                           "is_correct": False,
                           "question_id": 26
                       },
                       {
                           "id": 78,
                           "title": "Масленников",
                           "is_correct": False,
                           "question_id": 26
                       },
                       {
                           "id": 79,
                           "title": "Джон Макклейн",
                           "is_correct": True,
                           "question_id": 27
                       },
                       {
                           "id": 80,
                           "title": "Корбен Даллас",
                           "is_correct": False,
                           "question_id": 27
                       },
                       {
                           "id": 81,
                           "title": "Кайл Риз",
                           "is_correct": False,
                           "question_id": 27
                       },
                   ]
                   )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_status_id'), table_name='players_status')
    op.drop_table('players_status')
    op.drop_index(op.f('ix_answers_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_themes_id'), table_name='themes')
    op.drop_table('themes')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_difficulties_id'), table_name='difficulties')
    op.drop_table('difficulties')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
